import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 📡 OFDM-based Integrated Sensing and Communication (ISAC)\n",
            "> v5.2 - Professional Engineering Edition (Detection Fix)\n",
            "\n",
            "## 📑 1. Executive Summary\n",
            "This version provides a robust fix for target detection issues. The 2D CA-CFAR algorithm has been re-engineered to handle boundary conditions correctly and prevent target self-masking. The simulation now includes more realistic path loss and noise floor characteristics to validate detection performance."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from numpy.fft import fft, ifft, fftshift\n",
            "\n",
            "# Physical and Operational Constants\n",
            "C = 299792458.0\n",
            "FS = 20e6        # Increased bandwidth for better range resolution (15m -> 7.5m)\n",
            "FC = 5.8e9       # Using 5.8 GHz ISM band\n",
            "LAMBDA = C / FC\n",
            "PRI = 500e-6     # Faster PRI (0.5ms) to increase unambiguous velocity\n",
            "N_PULSES = 128   # More pulses for better Doppler resolution\n",
            "N_SC = 128       # More subcarriers\n",
            "CP = 32          # Cyclic Prefix\n",
            "N_SAMPLES = N_SC + CP\n",
            "\n",
            "range_res = C / (2 * FS)\n",
            "vel_res = LAMBDA / (2 * N_PULSES * PRI)\n",
            "\n",
            "print(f\"Range Resolution: {range_res:.2f} m\")\n",
            "print(f\"Velocity Resolution: {vel_res:.2f} m/s\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def generate_ofdm_stream(n_symbols):\n",
            "    data = (np.random.choice([-1, 1], (n_symbols, N_SC)) + \n",
            "            1j * np.random.choice([-1, 1], (n_symbols, N_SC))) / np.sqrt(2)\n",
            "    ofdm_time = ifft(data, axis=1)\n",
            "    cp = ofdm_time[:, -CP:]\n",
            "    return np.hstack([cp, ofdm_time]).flatten()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def simulate(targets, SNR_dB=25):\n",
            "    ref = []\n",
            "    surv = []\n",
            "    freqs = np.fft.fftfreq(N_SAMPLES)\n",
            "\n",
            "    for p in range(N_PULSES):\n",
            "        sig = generate_ofdm_stream(1)\n",
            "        sig /= np.sqrt(np.mean(np.abs(sig)**2))\n",
            "        ref.append(sig)\n",
            "\n",
            "        echo = np.zeros_like(sig, dtype=complex)\n",
            "        for t in targets:\n",
            "            delay = (2 * t['R'] / C) * FS\n",
            "            fd = 2 * t['v'] / LAMBDA\n",
            "            \n",
            "            # Fractional delay and Doppler\n",
            "            sig_f = np.fft.fft(sig)\n",
            "            shifted = np.fft.ifft(sig_f * np.exp(-1j * 2 * np.pi * freqs * delay))\n",
            "            doppler_phase = np.exp(1j * 2 * np.pi * fd * p * PRI)\n",
            "            \n",
            "            # Radar Equation: Power ~ 1/R^4 -> Amplitude ~ 1/R^2\n",
            "            # Normalized at 100m for simulation stability\n",
            "            loss = (100 / max(t['R'], 10))**2\n",
            "            echo += shifted * doppler_phase * t['amp'] * loss\n",
            "\n",
            "        # AWGN normalized to signal power\n",
            "        noise_std = np.sqrt(1 / (10**(SNR_dB / 10)) / 2)\n",
            "        noise = noise_std * (np.random.randn(N_SAMPLES) + 1j * np.random.randn(N_SAMPLES))\n",
            "\n",
            "        # Strong Direct Path Leakage (standard in passive radar)\n",
            "        direct_path = 5.0 * sig \n",
            "        surv.append(direct_path + echo + noise)\n",
            "\n",
            "    return np.array(ref), np.array(surv)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def process(ref, surv):\n",
            "    # Range Compression with Chebychev or Hanning for better sidelobe control\n",
            "    # We use Hanning here for simplicity but apply it to the correlation\n",
            "    corr = fft(surv, axis=1) * np.conj(fft(ref, axis=1))\n",
            "    corr *= np.hanning(N_SAMPLES)\n",
            "    rp = ifft(corr, axis=1)\n",
            "\n",
            "    # MTI: 3-pulse canceller for better notch at DC\n",
            "    # y[n] = x[n] - 2x[n-1] + x[n-2]\n",
            "    mti = rp[2:] - 2*rp[1:-1] + rp[:-2]\n",
            "    \n",
            "    # Doppler Processing with Windowing\n",
            "    mti *= np.hanning(mti.shape[0])[:, np.newaxis]\n",
            "    rd = fftshift(fft(mti, axis=0), axes=0)\n",
            "    return rd"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def cfar_2d(rd, guard=(4, 4), train=(8, 8), pfa=1e-5):\n",
            "    \"\"\"\n",
            "    Robust 2D CA-CFAR with boundary compensation and integral images.\n",
            "    \"\"\"\n",
            "    power = np.abs(rd)**2\n",
            "    rows, cols = power.shape\n",
            "    \n",
            "    # Integral image of power\n",
            "    S = np.zeros((rows + 1, cols + 1))\n",
            "    S[1:, 1:] = np.cumsum(np.cumsum(power, axis=0), axis=1)\n",
            "    \n",
            "    # Integral image of counts (to handle edges)\n",
            "    C_map = np.ones_like(power)\n",
            "    Sc = np.zeros((rows + 1, cols + 1))\n",
            "    Sc[1:, 1:] = np.cumsum(np.cumsum(C_map, axis=0), axis=1)\n",
            "\n",
            "    def get_area_sum(mat, r1, c1, r2, c2):\n",
            "        r1, r2 = np.clip([r1, r2+1], 0, rows)\n",
            "        c1, c2 = np.clip([c1, c2+1], 0, cols)\n",
            "        return mat[r2, c2] - mat[r1, c2] - mat[r2, c1] + mat[r1, c1]\n",
            "\n",
            "    det = np.zeros_like(power, dtype=bool)\n",
            "    \n",
            "    gr, gc = guard\n",
            "    tr, tc = train\n",
            "    \n",
            "    for i in range(rows):\n",
            "        for j in range(cols):\n",
            "            # Training + Guard window\n",
            "            total_sum = get_area_sum(S, i-tr-gr, j-tc-gc, i+tr+gr, j+tc+gc)\n",
            "            total_cnt = get_area_sum(Sc, i-tr-gr, j-tc-gc, i+tr+gr, j+tc+gc)\n",
            "            \n",
            "            # Guard window\n",
            "            guard_sum = get_area_sum(S, i-gr, j-gc, i+gr, j+gc)\n",
            "            guard_cnt = get_area_sum(Sc, i-gr, j-gc, i+gr, j+gc)\n",
            "            \n",
            "            n_cells = total_cnt - guard_cnt\n",
            "            if n_cells > 0:\n",
            "                noise_floor = (total_sum - guard_sum) / n_cells\n",
            "                alpha = n_cells * (pfa**(-1/n_cells) - 1)\n",
            "                if power[i, j] > alpha * noise_floor:\n",
            "                    det[i, j] = True\n",
            "    return det"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def visualize(rd, det, targets):\n",
            "    n_dopp, n_rng = rd.shape\n",
            "    ranges = np.arange(n_rng) * range_res\n",
            "    doppler_res = 1 / (N_PULSES * PRI)\n",
            "    doppler = (np.arange(n_dopp) - n_dopp//2) * doppler_res\n",
            "    \n",
            "    plt.figure(figsize=(12, 5))\n",
            "    \n",
            "    plt.subplot(1, 2, 1)\n",
            "    plt.imshow(20*np.log10(np.abs(rd)+1e-6), aspect='auto', cmap='jet',\n",
            "               extent=[ranges[0], ranges[-1], doppler[0], doppler[-1]])\n",
            "    plt.title(\"Range-Doppler Map (dB)\")\n",
            "    plt.colorbar(label=\"Intensity (dB)\")\n",
            "    plt.xlabel(\"Range (m)\")\n",
            "    plt.ylabel(\"Doppler (Hz)\")\n",
            "\n",
            "    plt.subplot(1, 2, 2)\n",
            "    plt.imshow(det, aspect='auto', cmap='gray',\n",
            "               extent=[ranges[0], ranges[-1], doppler[0], doppler[-1]])\n",
            "    plt.title(\"CFAR Detections\")\n",
            "    plt.xlabel(\"Range (m)\")\n",
            "    \n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "targets = [\n",
            "    {\"R\": 150, \"v\": 25, \"amp\": 2.0},\n",
            "    {\"R\": 400, \"v\": -15, \"amp\": 1.5},\n",
            "    {\"R\": 650, \"v\": 5, \"amp\": 1.0}\n",
            "]\n",
            "\n",
            "ref, surv = simulate(targets)\n",
            "rd = process(ref, surv)\n",
            "det = cfar_2d(rd)\n",
            "visualize(rd, det, targets)"
        ]
    }
]

notebook = {\"cells\": cells, \"metadata\": {}, \"nbformat\": 4, \"nbformat_minor\": 5}
with open('v5-2_pro.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
